spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(/zFDkd48Sk1JwrD7LjRJw9NgI8h4okFcm5fUMtp6RV1AA7T5j5BJNI6jCdiF/DhX)
    url: jdbc:mysql://119.45.61.2:3306/hush?setUnicode=true&characterEncoding=utf8
  thymeleaf:
    cache: false
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
mybatis-plus:
  type-aliases-package: com.blog.hush.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

logging:
  level:
    com.blog.hush.mapper: DEBUG
jasypt:
  encryptor:
    password: a1b2c3d4